language: node_js

node_js:
    - "7"

cache:
    directories:
        - "node_modules"

before_script:
    - "npm install"
    - "npm run lint"
    - "npm test"

after_success:
    - "npm run build-storybook"
